---
all:
  children:
    master:
      hosts:
        # Todo: ansible_hostをマスターノードのIPに変更
        master_1:
          ansible_host: 172.16.55.50
    worker:
      # Todo: ansible_hostをワーカーノードに変更
      hosts:
        worker_1:
          ansible_host: 172.16.55.51
        worker_2:
          ansible_host: 172.16.55.52
        worker_3:
          ansible_host: 172.16.55.53
        worker_4:
          ansible_host: 172.16.55.54
