---
all:
  children:
    master:
      hosts:
        master_1:
          ansible_host: 172.16.55.50
    worker:
      hosts:
        worker_1:
          ansible_host: 172.16.55.51
        worker_2:
          ansible_host: 172.16.55.52
        worker_3:
          ansible_host: 172.16.55.53
