- name: Setup kernel parameters
  hosts: master_1
  become: yes
  tasks:
  - name: Copy kernel module for containerd
    copy:
      src: ./files/containerd.conf
      dest: /etc/modules-load.d/containerd.conf/
      backup: true
  - name: Apply overlay module
    modprobe:
      name: overlay
      state: present
  - name: Apply br_netfilter module
    modprobe:
      name: br_netfilter
      state: present
  - name: Set kernel params
    copy:
      src: ./files/99-kubernetes-cri.conf
      dest: /etc/sysctl.d
      backup: true
  - name: Apply kernel params
    command: sysctl --system
  - name: Install dependencies (1)
    apt:
      name: ["ca-certificates", "curl", "gnupg", "lsb-release"]
      update_cache: yes
  - name: Create keyrings directory
    file:
      state: directory
      path: /etc/apt/keyrings
      mode: 0755

