- name: Create kubernetes join command
  hosts: master_1
  become: yes
  tasks:
  - name: Create kubeadm join command
    command: kubeadm token create --print-join-command
    register: join_cmd
  - name: Share join command
    set_fact:
      join_cmd: "{{ join_cmd.stdout }}"

- name: Join to cluster
  hosts: worker
  become: yes
  tasks:
  - name: Join to cluster
    command: "${{ join_cmd }}"
