- name: Setup kernel parameters
  hosts: master_1
  become: yes
  tasks:
  - name: Copy kernel module for containerd
    copy:
      src: ./files/containerd.conf
      dest: /etc/modules-load.d/containerd.conf/
      backup: true
  - name: Apply overlay module
    modprobe:
      name: overlay
      state: present
  - name: Apply br_netfilter module
    modprobe:
      name: br_netfilter
      state: present
  - name: Set kernel params
    copy:
      src: ./files/99-kubernetes-cri.conf
      dest: /etc/sysctl.d
      backup: true
  - name: Apply kernel params
    command: sysctl --system
  - name: Install dependencies (1)
    apt:
      name: ["ca-certificates", "curl", "gnupg", "lsb-release"]
      update_cache: yes
  - name: Create keyrings directory
    file:
      state: directory
      path: /etc/apt/keyrings
      mode: 0755
  - name: Save docker keyring
    apt_key:
      url: https://download.docker.com/linux/ubuntu/gpg
      keyring: /etc/apt/keyrings/docker.gpg
  - name: Set dpkg arch
    set_fact:
      dpkg_arch: "{{ 'amd64' if ansible_architecture == 'x86_64' else ansible_architecture }}"
  - name: Add docker to apt-repository
    apt_repository:
      repo: "deb [arch={{ dpkg_arch }} signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
  - name: Install dependencies (2)
    apt:
      name: containerd.io
      update_cache: yes
  - name: Create containerd directory
    file:
      state: directory
      path: /etc/containerd
  - name: Copy containerd config
    copy:
      src: ./files/containerd_config.toml
      dest: /etc/containerd/config.toml
      backup: true
