- name: Setup kubernetes master node
  hosts: master_1
  become: yes
  tasks:
  - name: Create bootstrap token
    shell: "echo $(openssl rand -hex 3).$(openssl rand -hex 8)"
    register: bootstrap_token
  - name: Copy kubeadm init config
    template:
      src: ./files/init_kubelet.yaml.j2
      dest: ~/init_kubelet.yaml
  - name: Initialize kubeadm
    command: kubeadm init --config=/root/init_kubelet.yaml
  - name: Get kube admin config
    fetch:
      src: /etc/kubernetes/admin.conf
      dest: outputs

- name: Setup kubernetes local
  hosts: localhost
  tasks:
  - name: Copy kube config
    copy:
      src: outputs/master_1/etc/kubernetes/admin.conf
      dest: ~/.kube/config
  - name: Install helm
    command: curl https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3 | bash
  - name: Add cilium to repo
    command: helm repo add cilium https://helm.cilium.io/
  - name: Install cilium
    command: helm install cilium cilium/cilium --namespace kube-system
